import { Herr_Von_Muellerhoff } from 'next/font/google'

const herrVonMuellerhoff = Herr_Von_Muellerhoff({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-herr',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={herrVonMuellerhoff.variable}>
      <body>{children}</body>
    </html>
  )
}
